export const darkFinanceTokens = {
  color: {
    background: {
      canvas: "#0B0F14",
      panel: "#10161F",
      elevated: "#151D28",
      inset: "#080C11",
    },
    border: {
      subtle: "#202A36",
      default: "#2B3745",
      strong: "#3B4A5C",
      focus: "#4DA3FF",
    },
    text: {
      primary: "#E6EDF3",
      secondary: "#9DA7B3",
      muted: "#687483",
      inverse: "#081018",
    },
    market: {
      bull: "#26A69A",
      bullMuted: "#153E3A",
      bear: "#EF5350",
      bearMuted: "#4A2022",
      neutral: "#8B949E",
    },
    accent: {
      primary: "#4DA3FF",
      gold: "#F0B90B",
      amber: "#C98A4B",
      violet: "#9A86C9",
      success: "#7EE2A8",
      warning: "#F2C94C",
      danger: "#FF6B6B",
    },
    chart: {
      grid: "#1C2530",
      axis: "#2B3745",
      crosshair: "#607086",
      ema20: "#F0B90B",
      previousDay: "#C98A4B",
      previousClose: "#9A86C9",
      todayOpen: "#4DA3FF",
      premarket: "#5D8A5F",
    },
  },
  typography: {
    family: {
      sans: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      mono: "'JetBrains Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
    },
    size: {
      xs: "0.6875rem",
      sm: "0.75rem",
      md: "0.875rem",
      lg: "1rem",
      xl: "1.25rem",
      display: "2rem",
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      tight: 1.2,
      normal: 1.5,
      relaxed: 1.7,
    },
    numeric: {
      fontVariantNumeric: "tabular-nums lining-nums",
      letterSpacing: "0.01em",
    },
  },
  spacing: {
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
  },
  radius: {
    none: "0",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    pill: "999px",
  },
  shadow: {
    panel: "0 8px 24px rgba(0, 0, 0, 0.28)",
    floating: "0 16px 48px rgba(0, 0, 0, 0.42)",
    focus: "0 0 0 3px rgba(77, 163, 255, 0.22)",
  },
  motion: {
    fast: "100ms",
    normal: "180ms",
    slow: "280ms",
    easing: "cubic-bezier(0.2, 0, 0, 1)",
  },
  chart: {
    candleBodyWidthRatio: 0.64,
    minimumBodyHeight: 1,
    pricePaddingRatio: 0.05,
    gridLineWidth: 1,
    keyLevelDash: [5, 4] as const,
  },
} as const;

export type DarkFinanceTokens = typeof darkFinanceTokens;

export const darkFinanceCssVariables = {
  "--pa-bg-canvas": darkFinanceTokens.color.background.canvas,
  "--pa-bg-panel": darkFinanceTokens.color.background.panel,
  "--pa-bg-elevated": darkFinanceTokens.color.background.elevated,
  "--pa-border": darkFinanceTokens.color.border.default,
  "--pa-text-primary": darkFinanceTokens.color.text.primary,
  "--pa-text-secondary": darkFinanceTokens.color.text.secondary,
  "--pa-text-muted": darkFinanceTokens.color.text.muted,
  "--pa-market-bull": darkFinanceTokens.color.market.bull,
  "--pa-market-bear": darkFinanceTokens.color.market.bear,
  "--pa-accent-primary": darkFinanceTokens.color.accent.primary,
  "--pa-accent-gold": darkFinanceTokens.color.accent.gold,
  "--pa-chart-grid": darkFinanceTokens.color.chart.grid,
  "--pa-chart-ema20": darkFinanceTokens.color.chart.ema20,
  "--pa-font-sans": darkFinanceTokens.typography.family.sans,
  "--pa-font-mono": darkFinanceTokens.typography.family.mono,
} as const;
